[package]
name = "cargo-fill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8"
cargo_toml = "0.16"
smallstr = "0.3"
promptly = "0.3"
crossbeam = "0.8"
